version: 0.2

phases:
  build:
    commands:
      - echo "No build needed – uploading to S3"

artifacts:
  files:
    - "**/*"
  base-directory: .
  discard-paths: no
  name: none
  destination: hygo.pdftohtml
